<!DOCTYPE html>
<html>
    <head>
        <title>Slave</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">

        <!-- Favicon -->

        <!-- CSS -->
        <link href="/css/default.css" rel="stylesheet" media="screen">

        <!-- JS -->
        <script src="/js/jquery-1.11.0.min.js"></script>
    </head>
    <body>
        <!-- Container das notificações -->
        <div class='notifications top-right'></div>

        <?php
        //Recupera e exibe as mensagens salvas na sessão
        Util_Notificacao::exibir();
        ?>

        <!-- Header -->
        <header id="sp-header-wrapper" class="">
            <div class="container">
                <div class="row-fluid" id="header">
                    <div id="sp-logo" class="span3">
                        <div class="logo-wrapper">
                            <div class="logo" style="width:153px; height:50px;"></div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <div class="clear"></div>

        <!-- Menu -->
        <div class="menu">
            <div class="menu-item">Publicação</div>
            <div class="clear"></div>
        </div>
        
        <!-- Body -->
        <div class="dvBody">
            <?php echo $this->layout()->content ?>
        </div>
        <div class="clear"></div>

        <!-- Footer -->

    </body>
</html>